class Semantic_cube:

    def __init__(self):
        self.cube = {
            'int': {
                'int': {
                    '+':'int',
                    '-':'int',
                    '*':'int',
                    '/':'dec',
                    '==':'bool',
                    '!=':'bool',
                    '>':'bool',
                    '<':'bool',
                    '>=':'bool',
                    '<=':'bool',
                },
                'dec': {
                    '+':'dec',
                    '-':'dec',
                    '*':'dec',
                    '/':'dec',
                    '==':'bool',
                    '!=':'bool',
                    '>':'bool',
                    '<':'bool',
                    '>=':'bool',
                    '<=':'bool',
                },
                'string': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'bool': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
            },
            'dec': {
                'int': {
                    '+':'dec',
                    '-':'dec',
                    '*':'dec',
                    '/':'dec',
                    '==':'bool',
                    '!=':'bool',
                    '>':'bool',
                    '<':'bool',
                    '>=':'bool',
                    '<=':'bool',
                },
                'dec': {
                    '+':'dec',
                    '-':'dec',
                    '*':'dec',
                    '/':'dec',
                    '==':'bool',
                    '!=':'bool',
                    '>':'bool',
                    '<':'bool',
                    '>=':'bool',
                    '<=':'bool',
                },
                'string': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'bool': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
            },
            'string':{
                'int': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'dec': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'string': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'bool',
                    '!=':'bool',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'bool': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
            },
            'bool': {
                'int': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'dec': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'string': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'error',
                    '!=':'error',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
                'bool': {
                    '+':'error',
                    '-':'error',
                    '*':'error',
                    '/':'error',
                    '==':'bool',
                    '!=':'bool',
                    '>':'error',
                    '<':'error',
                    '>=':'error',
                    '<=':'error',
                },
            }
        }

